version: "3.8"
services:
  flask_model:
    build:
      context: .
    container_name: flask_model
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
    - backend_net
   
networks:
  backend_net:
    external: true


