version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - backend_net

  flask_model:
    build:
      context: .
    container_name: flask_model
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - model_cache:/root/.cache
    networks:
      - backend_net
    depends_on:
      - qdrant

networks:
  backend_net:
    external: true  

volumes:
  qdrant_storage:
  model_cache:
