name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "QDRANT_HOST=qdrant" >> .env
          echo "QDRANT_PORT=6333" >> .env
          echo "URL_ARTICLE=http://dummy-url.com" >> .env
          echo "API_KEY_ETL=dummy-key" >> .env
          echo "API_KEY=super-secret-test-key" >> .env
          grep -v 'external: true' docker-compose.yml > docker-compose.tmp && mv docker-compose.tmp docker-compose.yml

      - name: Build and Start Services
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Wait for Services
        run: sleep 20

      - name: Initialize Database with Mocked Data
        run: docker compose exec flask_model python run_ci_startup.py

      - name: Run Pytest
        run: docker compose exec flask_model pytest --cov=app

      - name: Stop Services
        if: always()
        run: docker compose down