name: CI Pipeline - Tests de l'API IA

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "QDRANT_HOST=${{ secrets.QDRANT_HOST }}" >> .env
          echo "QDRANT_PORT=${{ secrets.QDRANT_PORT }}" >> .env
          echo "URL_ARTICLE=${{ secrets.URL_ARTICLE }}" >> .env
          echo "API_KEY_ETL=${{ secrets.API_KEY_ETL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
      - name: Debug file content
        run: |
          echo "--- Listing files in the current directory: ---"
          ls -la
          echo "--- Content of docker-compose.ci.yml: ---"
          cat docker-compose.ci.yml
      
      - name: Construire et démarrer les conteneurs
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Attendre que les services soient prêts
        run: sleep 15

   
      - name: Lancer les tests avec pytest
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml exec flask_model pytest --cov=app

      
      - name: Arrêter les conteneurs
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down