name: CI Pipeline - Tests de l'API IA

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "QDRANT_HOST=${{ secrets.QDRANT_HOST }}" >> .env
          echo "QDRANT_PORT=${{ secrets.QDRANT_PORT }}" >> .env
          echo "URL_ARTICLE=${{ secrets.URL_ARTICLE }}" >> .env
          echo "API_KEY_ETL=${{ secrets.API_KEY_ETL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Remove 'external: true' from docker-compose.yml
        run: grep -v 'external: true' docker-compose.yml > docker-compose.tmp && mv docker-compose.tmp docker-compose.yml

      - name: Display critical files for debugging
        run: |
          echo "--- Content of docker-compose.yml after modification: ---"
          cat docker-compose.yml
          echo "---"
          echo "--- Content of app/routes/search.py: ---"
          cat app/routes/search.py
      
      - name: Build and start containers (no cache)
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Lancer les tests avec pytest
        run: docker compose exec flask_model pytest --cov=app

      - name: Stop containers
        if: always()
        run: docker compose down