name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment and Debug Files
        run: |
          echo "--- Setting up .env file ---"
          echo "QDRANT_HOST=qdrant" >> .env
          echo "QDRANT_PORT=6333" >> .env
          echo "URL_ARTICLE=${{ secrets.URL_ARTICLE }}" >> .env
          echo "API_KEY_ETL=${{ secrets.API_KEY_ETL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          
          echo "--- Modifying docker-compose.yml for CI ---"
          grep -v 'external: true' docker-compose.yml > docker-compose.tmp && mv docker-compose.tmp docker-compose.yml
          
          echo "--- Displaying modified docker-compose.yml ---"
          cat docker-compose.yml
          
          echo "--- Displaying app/routes/search.py ---"
          cat app/routes/search.py

      - name: Build and Start Services
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Wait for Services
        run: sleep 20

      - name: Run Pytest
        run: docker compose exec flask_model pytest --cov=app

      - name: Stop Services
        if: always()
        run: docker compose down