name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "QDRANT_HOST=qdrant" >> .env
          echo "QDRANT_PORT=6333" >> .env
          echo "URL_ARTICLE=http://dummy-url.com" >> .env
          echo "API_KEY_ETL=dummy-key" >> .env
          echo "API_KEY=super-secret-test-key" >> .env
          grep -v 'external: true' docker-compose.yml > docker-compose.tmp && mv docker-compose.tmp docker-compose.yml

      - name: Build and Start Services
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Wait for Services
        run: sleep 20

      - name: Initialize Database with Mocked Data
        run: docker compose exec flask_model python run_ci_startup.py

      - name: Run Pytest
        run: docker compose exec flask_model pytest --cov=app

      - name: Stop Services
        if: always()
        run: docker compose down


  deploy-to-registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        id: repo_sanitized
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | sed 's#/$##')
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo_sanitized.outputs.repo_name }}/flask_ml_api:latest
            ghcr.io/${{ steps.repo_sanitized.outputs.repo_name }}/flask_ml_api:${{ github.sha }}
          file: ./Dockerfile